name: test

on: [push]

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-20.04]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: Dependencies
              run: sudo apt install libopenmpi-dev

            - name: Test
              run: make test
